<Root>
    BoxLayout:
        orientation:"vertical"
        size:root.width,root.height
        padding:50
        spacing:20
        Label:
            id:label
            text:"Hello"
            font_size:32
        Button:
            text:"Click me.."
            font_size:30
            size_hint:.5,.5
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:root.animate(self)