<Root>
    BoxLayout:
        size:root.width,root.height
        orientation:"vertical"

        Carousel:
            direction:"right"
            Label:
                text:"1"
                font_size:45
            Button:
                text:"Button 1"
                font_size:35
            Label:
                text:"2"
                font_size:45
            Button:
                text:"Button 2"
                font_size:35
